#spring.application.name=company-service
job-service.url=http://localhost:8082
company-service.url=http://localhost:8081
review-service.url=http://localhost:8083

server.port=8081
#for h2 database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true

#PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/company
#spring.datasource.url=jdbc:postgresql://localhost:5432/company?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=user
spring.datasource.password=user
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#EUREKA
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.application.name=company-service

#ZIPKIN
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://zipkin:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

#Rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest



